version: '1.3.6'
type: 'sw.application'
slug: g_benson_johnson/hvac
name: SBC-HVAC
application:
  type: microservices
services:
  - name: sensor-controller
    build: ./sensor-controller
  - name: web-interface
    build: ./web-interface
  - name: nginx-proxy
    build: ./nginx-proxy
  - name: influx-logger
    build: ./influx-logger
  - name: mosquitto
    build: ./mosquitto
    restart: always
  - name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
