version: '2'
services:
  relay-controller:
    build: ./relay-controller
    restart: always
    depends_on:
      -  sensor-processing
  sensor-processing:
    build: ./sensor-processing
    restart: always
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
#    depends_on:
#      - mosquitto
#  mosquitto:
#    build: ./mosquitto
#    restart: always
#    ports:
#      - "1883:1883"
  web-interface:
    build: ./web-interface
    depends_on:
      - relay-controller
  nginx-proxy:
    build: ./nginx-config
    ports:
      - "80:80"
    depends_on:
      - web-interface
      - sensor-controller
  influx-logger:
    build: ./influx-logger
    depends_on:
      - relay-controller
    environment:
      - API_URL=http://relay-controller:5000/getstatus
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=YourInfluxDBTokenHere
      - INFLUXDB_ORG=YourOrgName
      - INFLUXDB_BUCKET=YourBucketName
      - LOCATION=thermostat
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: