version: '2'
services:
  sensor-controller:
    build: ./sensor-controller
    restart: always
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
  emqx:
    image: emqx/emqx:latest-arm64
    restart: always
    environment:
      EMQX_NAME=thermostat
      EMQX_CLUSTER__DISCOVERY=strict
      EMQX_NODE__NAME=node@thermostat
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8081:8081"
      - "4369:4369"
      - "5369:5369"
  web-interface:
    build: ./web-interface
    depends_on:
      - sensor-controller
  nginx-proxy:
    build: ./nginx-config
    ports:
      - "80:80"
    depends_on:
      - web-interface
      - sensor-controller
  influx-logger:
    build: ./influx-logger
    depends_on:
      - sensor-controller
    environment:
      - API_URL=http://sensor-controller:5000/getstatus
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=YourInfluxDBTokenHere
      - INFLUXDB_ORG=YourOrgName
      - INFLUXDB_BUCKET=YourBucketName
      - LOCATION=thermostat
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: