version: '2'
services:
  sensor-controller:
    build: ./sensor-controller
    restart: always
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true

  web-interface:
    build: ./web-interface

  nginx-proxy:
    build: ./nginx-config
    ports:
      - "80:80"
    depends_on:
      - web-interface
      - sensor-controller