name: Deploy to Balena

on:
  push:
    branches:
      - main

jobs:
  balena_cloud_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: g_benson_johnson/hvac
        id: balena_deploy

      - name: Log release ID built
        run: echo "Built release ID ${{ steps.balena_deploy.outputs.release_id }}"
