name: Deploy to Balena

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Balena
      uses: balena-io-playground/balena-login-action@master
      with:
        balena_token: ${{ secrets.BALENA_TOKEN }}

    - name: Push to Balena
      run: |
        balena push hvac
